apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appId: nginx
  name: nginx-test
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        appId: nginx
    spec:
      containers:
      - name: nginx
        image: nginx